{
 "title": "Keycloak",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/keycloak\"} |= `LOGIN_ERROR`"
    }
   ]
  },
  {
   "title": "Max Connection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_connections_seconds_max{server_port=\"8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Management Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_connections_seconds_max{server_port=\"8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_bytes_written_sum{server_port=\"8080\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_active_connections{server_port=\"8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}