{
 "title": "OpenLDAP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Uptime,cn=Time,cn=Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Active,cn=Threads,cn=Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Search,cn=Operations,cn=Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Bind,cn=Operations,cn=Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Total,cn=Connections,cn=Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Current,cn=Connections,cn=Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenLDAP Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "openldap_monitor_operation", "legendFormat": "__auto" }
   ]
  }
 ]
}