include         /etc/openldap/schema/core.schema
include         /etc/openldap/schema/cosine.schema
include         /etc/openldap/schema/inetorgperson.schema
include         /etc/openldap/schema/nis.schema

modulepath      /usr/lib/openldap
moduleload      back_mdb.so


TLSCACertificateFile  /etc/openldap/certs/ca.crt
TLSCertificateFile    /etc/openldap/certs/ldap.crt
TLSCertificateKeyFile /etc/openldap/certs/ldap.key
TLSDHParamFile        /etc/openldap/certs/dhparam.pem
TLSVerifyClient       never

database        mdb
maxsize         1073741824
suffix          "dc=example,dc=in"
rootdn          "cn=admin,dc=example,dc=in"
rootpw          {SSHA}6/xfSHt1a1K8SC0uhjETD+7WEf5A3Vx9
directory       /var/lib/openldap/openldap-data
index           objectClass eq

database        monitor
access to dn.subtree="cn=Monitor"
    by dn.exact="cn=admin,dc=example,dc=in" read
    by * none
